# Setup
title:               Down to the Wire
url:                 https://downtothewire.io
baseurl:             /blog
permalink:           pretty

# Contents
exclude:             [CNAME, Gemfile, Gemfile.lock, README.md, LICENSE]
unpublished:         true
show_drafts:         true
livereload:          true

# Custom data
established:         2014
license:             CC BY 4.0
license_url:         https://creativecommons.org/licenses/by/4.0/legalcode

# Plugins
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

kramdown:
  smart_quotes:  ["apos", "apos", "quot", "quot"]

# Pages
collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: "_drafts"
    values:
      layout: "post"
      permalink: /posts/:title/
